### ISSUE TITLE
Return query results as pandas dataframe

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/gdsclient#3]
A lot of data scientists like to use pandas for various data aggregations and manipulations, so it would make sense to add another method that returns a pandas dataFrame.

Should be quite easy as the current return is a list of dicts, so all you need to use is to use

`pd.DataFrame.from_dict()`

**Comment by voutilad** [comment]
> Should be quite easy as the current return is a list of dicts...

That assumes a small enough dataset. Since `gdsclient` currently uses the Neo4j Python Driver, this won't scale.

**Comment by tomasonjo** [comment]
But the problem of scaling remains whether you return a dataframe or not?

**Comment by AliciaFrame** [comment]
@tomasonjo - dataframe support is on the roadmap for the official neo4j python driver, so we're waiting on them to implement that feature (versus implementing it ourselves)
